### ISSUE TITLE
Indexing messages broken after Thunderbird 52 update

### ISSUE THREAD

**Issue by BelzebubsGrandson** [protz/thunderbird-conversations#1184]
Hello,

After Thunderbird 52 update, Conversations add-on started acting weird as described in some of the previous issues: Sent emails do not show in the threads, Emails that should not be on the thread appearing etc.
It turned out that the Message Index Database is corrupted and after following steps on rebuilding database from [here](https://support.mozilla.org/t5/Troubleshooting/Rebuilding-the-Global-Database/ta-p/15801), Indexing Messages was stuck and didn't want to complete.
After disabling Conversations, Indexing Messages went through just fine and on re-enable, Conversations worked as intended, until new email is received and Indexing Messages process was stuck again so the process described above had to be repeated.
As a temporary solution, I have downgraded to Thunderbird version 45.8 [here](http://releases.mozilla.org/pub/thunderbird/releases/45.8.0/win32/en-US/) and disabled automatic updates as instructed [here](http://www.cnx-software.com/2011/10/05/disable-auto-update-for-thunderbird-and-firefox/).

Please let me know if any additional info is needed.
Thanks,
Pavle

**Comment by kumarpranay** [comment]
I can confirm the same behaviour on MacOS and have followed the suggestion above to revert to 45.8. Thanks.

**Comment by pianoslum** [comment]
For me (ArchLinux) some colors look a bit odd, but functionality-wise everthing seems ok.
What is your OS?
Could you test the latest version (https://jonathan.protzenko.fr/thunderbird-conversations/) with TB 52?

**Comment by boris-petrov** [comment]
I am on Arch Linux and even with the latest version (2.12pre, installed from `201702191737-master.xpi`) I still have the same issues.

**Comment by kumarpranay** [comment]
Upgraded to Thunderbird 52.0.1 again and installed 201702191737-master.xpi. Same results. The moment I disable the add-on indexing resumes, but with the add-on enabled the indexing is stuck where it is.

MacOS 10.12.4

**Comment by BelzebubsGrandson** [comment]
Hello,
I have installed 201702191737-master.xpi version of the add-on on Thunderbird 52, results are the same as described in my previous note.
OS is Windows 10.
Thanks!

**Comment by shatterjack** [comment]
Hi Pavle,

Just checking back in, what do you think?

**Comment by JuanCabre** [comment]
Hello,

I am having exactly the same issue with thunderbird version 52 and Conversations version 2.11.4

I am using Arch Linux.

Thanks for the support :smiley:

**Comment by sba** [comment]
same problem here - sent messages not showing in thread etc..

On windows 10 (1703)

**Comment by rnc** [comment]
I have also seen this on Fedora 25 with Thunderbird 52. I have tried with the 2.11.4 and master version. Downgrading to Thunderbird 48 *and* rebuilding the message database fixes the issue for me.

**Comment by pianoslum** [comment]
I can now confirm the same problems with the latest versions.
Currently, Jonathan (the addon's author) and me (not saying that I could locate the problem ;-)) are rather busy, so I don't know when we can provide a fix.

Does any of you mind digging into the addOn code?
@BelzebubsGrandson You seem to have some insight?

**Comment by BelzebubsGrandson** [comment]
Hello **pianoslum**, thank you taking the time too look into this!
As much as I'd like to help on this issue, I'm afraid I don't have the skills necessary. Sure I'll look into the code, but I don't have high hopes.
Hopefully, someone skillful enough will come along and resolve the issue before you guys find the time. If not, there's nothing else left but to wait. :)

Thanks once again,
Pavle

**Comment by snowbound** [comment]
I upgraded to 52.0.1 and some how Conversations 2.11.4 became disabled. I re-enabled it and the replies showed up fine in with the inbox messages. However the next time I started Thunderbird up the replies were again not showing up.

**Comment by oaschwab** [comment]
I also am having this issue. I tried deleting MSF files and the SQLITE files but the only way to fix it was to disable this addon.

**Comment by pmbrandao** [comment]
Just to add a small point, if you delete the global-messages-db.sqlite and restart Thunderbird (as instructed to [rebuild the global database for search](https://support.mozilla.org/en-US/kb/rebuilding-global-database)) the Tools -> Activity Manager will indicate "determining which messages to index in" indicating the folder it is working on.

**Comment by snowbound** [comment]
As it stands today this extension is of no use to people using Thunderbird 52.x if you want to be able to use Thunderbird's search functionality.  As it stands I have disabled the extension and will check in from time to time to see if anything becomes of it.

**Comment by adefaria** [comment]
I can vouch for the problem in 52.1 on Ubuntu 16.10.

**Comment by barenen** [comment]
Yep, running into the same issue here (Win10 Pro), TB52.1.0.

**Comment by ananthaprasadck** [comment]
Same issue, he conversation pluggin is not listing the related mails. The pluggin is not helping.

I am using Windows 10 Pro and Thunderbird 52.1.0 (32-bit).

**Comment by snowbound** [comment]
I would strongly advise any one using Conversations extension to disable it if you are using Thunderbird 52.x. This is because the plugin screws up the updating of a critical index file preventing you from performing meaningful and accurate searches for email messages. You can monitor this thread for any updates to this issue but as of today this extension is of no use in TB 52.x

**Comment by msreekanth** [comment]
Yes.i have installed the Conversations extension today. It worked fine for some time and then I saw the indexing got stuck for almost 4 hours

**Comment by kmhallen** [comment]
I can also confirm that the conversations extension breaks TB 52.x on Windows 10

**Comment by Standard8** [comment]
I think I've found the issue - I've raised #1189 as a PR to fix this, my Thunderbird 52 is now indexing with that patch incorporated onto the add-on.

**Comment by snowbound** [comment]
Well edited the modules/plugins/glodaAttrProviders.js in the XPI container for the extension as per  https://github.com/protz/thunderbird-conversations/pull/1189/commits/adfcd93640414f565c4f1c56c612119589acab93

Seems to be working ok. Indexing seems to be updating the index file properly.

**Comment by rnc** [comment]
Confirmed here too ; applied that patch updated thunderbird-52.1.0-1.fc25.x86_64 and its working fine- Thanks! :-)

**Comment by kumarpranay** [comment]
Same degree of success here after patching the last master xpi (I did not checkout from git). Will update if anything is amiss but from the looks of it we are back to working code.

**Comment by TimHiggison** [comment]
Confirmation here too, back to working perfectly after patching glodaAttrProviders.js.

**Comment by BelzebubsGrandson** [comment]
Hello guys,
After testing it for 2 days I can also confirm that Mark's patch fixed the issue and Conversations are working as intended. Great job Mark and thank you very much for this!

For people like me (noobs) who would have problems compiling the add-on with Mark's fix, I have uploaded complied Conversations Add-on to Dropbox [here](https://www.dropbox.com/s/ytrsy02jqgkycpq/conversations_indexing_fixed.xpi?dl=0).
Please let me know if this works.

Thanks,
Pavle

**Comment by rajeshstarlite** [comment]
I'm using Thunderbird 52.1.1 (64-bit) with Ubuntu 16.04. 

I am BIG FAN of Thunderbird Conversation but this https://www.dropbox.com/s/ytrsy02jqgkycpq/conversations_indexing_fixed.xpi?dl=0 didn't help me. 

Thunderbird Activity Manager doesn't stop from indexing since 40 minutes. I had exchanged only 15 emails. Please see screen shot.
![always-indexing](https://cloud.githubusercontent.com/assets/9151579/26250201/f3c298f6-3cc6-11e7-9908-9b6e6a7aff42.png)

**Comment by kroka** [comment]
I observe the same behavior as @rajeshstarlite on a similar system.

 * same problems as in #1192 
 * manually applying #1189 does not change anything (at least it seems like)
 * indexing is stuck in a small folder as long as _Thunderbird Conversations_ is enabled
 * replies are still not shown even after disabling the add-on, restarting Thunderbird (and successful indexing) and re-enabling the add-on

---
Thunderbird Conversations 2.11.4
Thunderbird 52.1.1 (64-Bit)
KDE Neon (based on Ubuntu 16.04)

**Comment by TimHiggison** [comment]
@kroka Can you list the steps you used to apply the patch? I had the exact same problem and it was gone the instant I updated the JS and restarted Thunderbird.

**Comment by kroka** [comment]
@TimHiggison After forcing a rebuild of the global database by deleting the _global-messages-db.sqlite_ (https://support.mozilla.org/en-US/kb/rebuilding-global-database) everything works fine now. Maybe my database was corrupted in some way (I don't know).

To sum up, #1189 worked for me as well though I had to rebuild the global database.

**Comment by JuanCabre** [comment]
I am having the same issue of "Determining which messages to index in sent" even after deleting the global database.

However, I am new with thunderbird addons. I am not sure how to install the patch. I thought that if I installed the version directly from Thunderbird add-on manager, the patched version would be running. Are there any additional steps to include the patch?

**Comment by kroka** [comment]
@JuanCabre The version you can install using the add-on manager probably won't work. You either have to
* modify the file _modules/plugins/glodaAttrProviders.js_ inside _$HOME/.thunderbird/<your profile>/extensions/gconversation@xulforum.org.xpi_ (which is basically a zipped file) according to #1189  or you
* install the already patched extension provided by @BelzebubsGrandson here: https://github.com/protz/thunderbird-conversations/issues/1184#issuecomment-302261536 (_(gear icon) > install from file_ in the add-on manager).

**Comment by JuanCabre** [comment]
@kroka thank you for the help. Everything seems to be working fine now :)

Now, out of curiosity, why does the version installed with the add-on manager do not work? I thought that changes to this repo would trigger thunderbird to update the add-on.

**Comment by kroka** [comment]
> I thought that changes to this repo would trigger thunderbird to update the add-on.

#1189 is just a request and was not accepted yet. Both _thunderbird-conversations/modules/plugins/glodaAttrProviders.js_ in this repository and especially the add-on from https://addons.mozilla.org/thunderbird/addon/gmail-conversation-view/ have not been updated, yet.

**Comment by rajeshstarlite** [comment]
@kroka Thank you very much. The steps I followed:

(1) I have installed the patched extension provided by @BelzebubsGrandson [#1184](https://github.com/protz/thunderbird-conversations/issues/1184#issuecomment-302261536) ((gear icon) > install from file in the add-on manager).
(2) Forced a rebuild of the global database by deleting the global-messages-db.sqlite (https://support.mozilla.org/en-US/kb/rebuilding-global-database)

Now Thunderbird started rebuild of the global database and all works fine now. Cheers!

**Comment by jonmmorgan** [comment]
I upgraded to Thunderbird 52 a couple of days ago, and installed the patched extension in the comment above yesterday.  Since then, Thunderbird has crashed three times (once before I forced a rebuild of the global database, twice afterwards).

General symptoms have been a message refusing to display at all in the preview window.  Once I switch to a different message, Thunderbird will crash in a couple of seconds.

This is on Windows 7, Thunderbird 52.1.1 (32-bit).

**Comment by TimHiggison** [comment]
Any info from the crash? Stack trace or any sort of dump to narrow down 
the issue?

**Comment by jonmmorgan** [comment]
Not that I could see, but I wouldn't know where to look.
I think it submitted a log to Mozilla.

**Comment by jonmmorgan** [comment]
Just FYI, I now think it is due to running out of memory.
Before it crashes, the preview window still shows the message headers in the threaded conversation, but the message contents go black in the same way as Firefox does when running out of memory.
I don't think it even suddenly spikes in memory usage, it just grows over several hours.

Seeing as I upgraded Thunderbird and Thunderbird Conversations at the same time I can't easily isolate which is responsible, so I'm not sure I can help you further.

**Comment by demis-palma** [comment]
I confirm the problem and the solution on Ubuntu 14.04.

**Comment by jonmmorgan** [comment]
Just as a final FYI, I found that I had a corrupted places.sqlite file in my profile, which seems to have been causing the memory issues.  When I removed the corrupted files, Thunderbird memory usage stopped spiking.
Sorry for the noise.

**Comment by koolx** [comment]
Looks like the problem has crept back. Replies have stopped being added below my recipient's responses. What do I do now?

**Comment by anderwm** [comment]
I have this problem as well now, on Ubuntu 16.04 and Thunderbird 52.2.0. It wasn't indexing new messages so I deleted the database file and it won't re-index. The activity manager just says "Determining which messages to index" forever.

**Comment by paulpremont** [comment]
I have restarted thunderbird in safe mode (all addons disabled) and it solve this problem. 
And refresh the database by deleting the file global-messages-db.sqlite.
Hope it will fork you also.

**Comment by harryd100** [comment]
Both topics are closed, does that mean there is a solution?

**Comment by das-peter** [comment]
The currently latest build [201706111701-2.13+.xpi](https://jonathan.protzenko.fr/thunderbird-conversations/201706111701-2.13+.xpi) available on Jonathan Protzenkos aka @protz [personal website](https://jonathan.protzenko.fr/thunderbird-conversations/) seems to work just fine with Thunderbird 52.2.1

**Comment by anderwm** [comment]
I still have to disable conversations every time I want my messages to index in 52.2.1 on ubuntu 16.04

**Comment by Taitava** [comment]
@anderwm It's not only your problem, I still have the same problem in 52.2.1 too. @das-peter Do you know when will this latest build get automatically updated to Thunderbird? Sorry, I'm new to how Thunderbird manages addons and updates them. I could download the plugin from the website you mentioned, but I would rather let Thunderbird to handle the updating in it's normal way.

**Comment by harryd100** [comment]
I'm on 16.04 , TB 52.2.1 and Conversations 2.12pre (no auto updates) and works fine.

**Comment by Standard8** [comment]
Hi, we're working on getting a new release of Conversations out soon, however the maintainer is quite busy at the moment, and we're waiting for him to get some time to be able to push it out.

**Comment by anderwm** [comment]
I was on 2.11 (which is what get's pushed to ubuntu 16.04 I guess), it does work on 2.12pre from the link above.

**Comment by das-peter** [comment]
@Taitava I don't think there's any automatism behind the release. It has be done by the maintainer of the add-on. Installing it from the mentioned website shouldn't be to much of a hassle: https://support.mozilla.org/en-US/kb/installing-addon-thunderbird#w_a-slightly-less-ideal-case-install-from-a-downloaded-xpi-file
However, I understand concerns - before I installed the add-on from there I did some cross checking about the domain / usernames / documentation and such to "verify" it's a valid source.

**Comment by folfy** [comment]
Updating to the referenced 2.12pre fixed the search for me as well (Win 10 x64), hope this gets pushed upstream soon for all the users with less patience and googling-skills.

> Just suddenly noticed that the search wasn't working any more, first trying to rebuild the database and then searching for the ever-lasting activity-message "firefox determining which messages to index" fortunately led me here...

**Comment by Standard8** [comment]
Hi everyone. I have just uploaded a pre-release version with this fix in to https://addons.mozilla.org/thunderbird/addon/gmail-conversation-view/#beta-channel (under the Development Channel section). The version number is 2.13pre1.

Please give it a try and file a new issue if you find a problem.

If all goes well I'll push it up for release later this week.

Note: It is likely not going to work in 56 & later (i.e. current beta/nightly). I need to look at porting some other fixes for that. If it doesn't happen before I release 2.13, it'll happen soon after.

**Comment by Standard8** [comment]
I've just released a new 2.13pre2 with a couple more bug fixes, including support for 56 (the current Thunderbird beta).

2.13pre2 is now on the development channel. If you've already downloaded from there, then Thunderbird should be able to auto-update it (you can force update by going to Tools -> Addons, click the cog icon, select "Check for updates).

57 (Thunderbird nightly) support needs a bit more work, which I won't have time for before I release 2.13.

**Comment by koolx** [comment]
Will the new update work on Thunderbird 52.3?

**Comment by Standard8** [comment]
Yes, any Thunderbird 52 version.

**Comment by koolx** [comment]
ok

**Comment by Standard8** [comment]
Good news, the updated add-on is now on AMO, if you haven't been on the beta channel, then you just need to let it update or go to Tools -> Addons, Click the cog icon and then select Check For Updates.

You might need to restart for the indexing to start working properly again.

It has support for any version of TB 52, and also TB 56 beta. Daily 57 support will hopefully come soon once I get a bit of time to fix that up.

If you find any issues, please file them as new. If you want to stay with the latest pre-release versions and help us test, please stay on the beta channel.

Thanks for the feedback everyone and to @protz for enabling me to help get this out.

**Comment by protz** [comment]
I've also pushed a new build to the server... just in case.

**Comment by mitra42** [comment]
I'm seeing this problem still - and it persists even if I disable Conversations, Quit, remove global-messages-db.sqlite and restart.  I only started using Conversations again recently after many years not using it (its missing too many important TB features) so I'm almost certain this is correlates with indexing stopping.  Conversations 2.13.3 TB 56.0b4 OSX High Sierra (fully updated); Let me know if you want me to test anything.

**Comment by koolx** [comment]
Theres a big bug in the latest Conversations. It wont let me copy links in mail. For example, when I highlight the following links, the right click menu doesn't come up at all:

https://www.amazon.com/dp/B01KNZAG0U
https://www.amazon.com/dp/B01KNZ8YUE
https://www.amazon.com/dp/B01KXAEN2M 

Somebody please fix and update this. Thanks.

**Comment by koolx** [comment]
Conversations isn't working anymore. Is there a fix???

**Comment by koolx** [comment]
Hi everyone,

There are parts of a message I can't copy when I right click. When I disable TC, copying works. It needs an update big time. Let me know!

**Comment by fllp** [comment]
@koolx: what you're describing in your last posts looks like a different issue not related to indexing.  
Have you checked the other open issues for your problem?  
If there is none yet, please report your problem in a new issue.

And just remember that the devs of TC are coding this on their spare time and are spread thin as it is. So demanding fixes every few days is not particularly helpful :wink:

**Comment by koolx** [comment]
@Flying Lollipop,

I never mentioned "indexing" so I don't know what you're talking about.

By "open issues" if you mean did others with the same issues resolve them the answer is obviously no since no one responded to me. Do you have a problem with viewing this forum correctly? Its clear that if others resolved an issue it would've been clearly posted.

Also I fail to see were you got that I was "demanding fixes" since I never urged such action. 

Just to let you know there are forum rules to obey. Let's put away our trolling slingshot.

**Comment by demis-palma** [comment]
koolx on 13 December:
> [Also I fail to see were you got that I was "demanding fixes"](https://github.com/protz/thunderbird-conversations/issues/1184#issuecomment-351546445)

koolx on 14 November:

> [Somebody please fix and update this. Thanks.](https://github.com/protz/thunderbird-conversations/issues/1184#issuecomment-344211578)

**Comment by demis-palma** [comment]
> Do you have a problem with viewing this forum correctly?

@koolx This is not a forum. It is an issue tracker, and in particular, this conversation belongs to a closed issue. 
Flying just wanted to say that you are wasting your time.

**Comment by Standard8** [comment]
This is indeed not a forum. I have now locked the conversation here as this issue is long closed. New issues should be filed in new bugs, preferably with complete steps to repeat and/or examples / images of the actual issues.
