### ISSUE TITLE
Thunderbird 68, Empty Attachment Issue

### ISSUE THREAD

**Issue by sahil48** [protz/thunderbird-conversations#1362]
* **Thunderbird version:** 68.0
* **Thunderbird Conversation version:** 2.15.8
* **Operating System:** Windows 10

**What did you do?** I tried to open an attachment from Thunderbird Conversations using the magnifying glass icon

**What did you expect to happen?** The Attachment would open.

**What actually happened?** I get the following error

![image](https://user-images.githubusercontent.com/6100774/64033122-ca4a5200-cb19-11e9-98e8-70521294d91e.png)

**Other Notes?** Interestingly enough, clicking the eye icon does still show a preview of the attachment. When I open the email using Thunderbird's standard email viewer, the attachment can also be opened.

Aside from that and Quick Reply unavailable, the addon is working good with the new version of the Thunderbird so far!

**Comment by Standard8** [comment]
@sahil48 What happens if you go to the little three-dot menu at the right of the message header, select "View using classic reader", then expand the attachment view at the bottom. Finally right click and select Open.

Does that work, or does that end in the same issue? If it is the same issue, then the failure is Thunderbird's rather than Conversations.

It could be Conversations - we've changed a little around how the UI works there, but I though we'd kept the same implementation as before (and it seems to work on all the cases I've tried).

**Comment by PxaMMaxP** [comment]
Hello,

I have the same problem under the same configuration. 
If I follow your instruction, I can get my attachments.

Second observation, on some mails the attachments will not shown anyway.

This mail has an attachment, with your instructions I can see them.
![test](https://user-images.githubusercontent.com/46793832/64170791-4d88e200-ce51-11e9-847f-aeaaf7607bc7.png)

**Comment by Standard8** [comment]
@PxaMMaxP From your second obseveration - the attachments not showing might be an issue I fixed yesterday. If you go to Tools -> Add-ons, and near the top-right is a cog symbol. Select that and "Check for updates". Assuming it updates, restart Thunderbird, and try viewing the mails again.

For the first one, it does indeed seem like an issue. Please can you go to the Three bar menu -> Tools -> Developer Tools -> Error Console. Once the Error console is open, clear it using the bin icon near the top-left, then select one of the broken emails, and try opening the attachment.

Do any errors appear? If so, please could you copy and paste them here.

**Comment by PxaMMaxP** [comment]
I have the now the Version 2.15.9 but the second problem is still existent.

Yes, I get this error on the first problem:
AttachmentInfo.isEmpty: error - data.value is undefined msgHdrView.js:1932:17

**Comment by Standard8** [comment]
Do you see any errors when viewing emails with the second problem?

Also, do these issues appear with IMAP, POP or local folders?

Are the attachments any special types? 

I'll have to have a dig a bit more later, but I can't currently find any attachments locally where I can reproduce this, which might make it difficult.

**Comment by sahil48** [comment]
Hi Mark,

To follow up with your question:
* Attachments work with gMail (I think I set it up via IMAP but cannot remember
* I am still getting the error for email accounts managed by a mail hosting by iPowerWeb (https://www.ipower.com/). I am using an IMAP account opening a pdf. The attachments work when I view with classic reader, so it is not a Thunderbird issue. Before the update, these attachments were available with Thunderbird Conversations.

![image](https://user-images.githubusercontent.com/6100774/64173559-9165f200-ce25-11e9-81e5-e737affadd16.png)

If you would like, if you could let me know a way I can contact you by email, I can set up a test email account for you to investigate this issue further sometime in the next 2 days.

**Comment by westwoodpr** [comment]
I'm having exactly the same issues and get the same messages with v2.15.9.

     "This attachment appears to be empty.
      Please check with the person who sent this.
      Often company firewalls or antivirus programs will destroy attachments."

     "Quick Reply is temporarily disabled due to needing more work for Thunderbird 68"

**Comment by Standard8** [comment]
I've just created [a version](https://www.thebanners.uk/conversations-attachment-debug.zip) with some extra debug output. Could someone try it please?

Don't expand the file, just install it, though you might need to change it to a .xpi extension.

Once installed:

* Open up the Error Console (Tools -> Developer Tools).
* Then visit a message message with attachments where you're having issues.
* At this stage the error console should log two or more objects. Right-click each of them in turn and select "Copy Object". Paste them into a text file.
* Then try clicking the open magnifying glass. Another object will appear on the error console, so please copy and paste that into the text file.
* Next try right-clicking the attachment and selecting "Open Attachment". I'd be interested if this works, it is a slightly different code path. Either way, copy the object, and paste into the text file.
* Finally, open the message in the classic reader, and try opening the attachment from there. Again, copy and paste the newly shown object from the error console to the text file.

Now check through the text file for anything you want to obscure. I'm quite happy for domain parts of urls (e.g. `me%40foo@myhost.com:993`) to be obscured, but it helps if you don't obsure the path.

I'm happy for names of attachments to be changed but if there's things like non-ascii characters or encoding, that would be potentially useful to preserve.

Other information like authors + recipients, subjects, can be completely removed if you want.

It is mainly the content types, urls, attachment names, sizes that are the important things here.

Finally, post the contents of the text file here and I'll take a look and see if I can figure out what's happening.

**Comment by Standard8** [comment]
Note, I've only instrumented opening attachments. I've not done save nor preview.

**Comment by sahil48** [comment]
Sure. Will it simply override the existing thunderbird installation? Do you have an email address I can send the logs to, so I do not have to sanitize the text file?

**Comment by westwoodpr** [comment]
Here are the console log entries after trying to open attachments:

On Thunderbird startup BEFORE visiting message with attachment:
error:
uncaught exception: 2147746065 autosync.jsm:199:30

logs:
PrefManager init prefs.js:44:11
No chrome package registered for chrome://enigmail/content/modules/core.jsm


AFTER LOGS CLEARED AND VISITING MESSAGE WITH ATTACHMENT:

error:
Security Error: Content at moz-nullprincipal:{964ecc8a-cbc2-4569-90c6-a4c4fbb5ff5f} may not load or link to chrome://conversations/content/stub.xhtml.
Warning: Invalid DOM property `contextmenu`. Did you mean `contextMenu`?
    in li (created by _Attachment)
    in _Attachment (created by ConnectFunction)
    in ConnectFunction (created by _Attachments)
    in div (created by _Attachments)
    in ul (created by _Attachments)
    in _Attachments (created by ConnectFunction)
    in ConnectFunction
    in Provider react-dom.js:500:32
SyntaxError: An invalid or illegal string was specified mailWidgets.js:578
SyntaxError: An invalid or illegal string was specified menulist-addrbooks.js:11
uncaught exception: 2147746065 autosync.jsm:199:30

warning:
Removing unsafe node. Element: select. jquery-3.2.1.min.js:2:10353
Removed unsafe URI from element attribute. Element: a. Attribute: href. jquery-3.2.1.min.js:2:10830
Removing unsafe node. Element: select. jquery-3.2.1.min.js:2:10830
Flattening unsafe node (descendants are preserved). Element: input. jquery-3.2.1.min.js:2:23229
Flattening unsafe node (descendants are preserved). Element: form. 2 jquery-3.2.1.min.js:4:18409

logs:
Object { renderAtt: (1) […] }
stub.xhtml:249:17

AFTER LOGS CLEARED AND CLICKING MAGNIFYING GLASS:
error:
uncaught exception: 2147746065 autosync.jsm:199:30

warning:
AttachmentInfo.isEmpty: error - data.value is undefined msgHdrView.js:1932:17


AFTER CLEARING LOGS AND RIGHT CLICKING ATTACHMENT:
warning:
AttachmentInfo.isEmpty: error - data.value is undefined msgHdrView.js:1932:17


AFTER CLEARING LOGS AND OPEN IN CLASSIC VIEW:
uncaught exception: 2147746065

**Comment by Standard8** [comment]
> Sure. Will it simply override the existing thunderbird installation of Conversations, or install alongside it? Do you have an email address I can send the logs to, so I do not have to sanitize the text file?

It will override the existing install - you probably also want to re-install the "official" version after trying it.

You can send emails to standard8 at mozilla dot com.


> Here are the console log entries after trying to open attachments:
Thanks for trying this.

> AFTER LOGS CLEARED AND VISITING MESSAGE WITH ATTACHMENT:
> Object { renderAtt: (1) […] }

Unfortunately, you need to actually right-click on this and select `Copy Object`, that gives the detail within it, which is what I really need here.

> AFTER LOGS CLEARED AND CLICKING MAGNIFYING GLASS:

I'm surprised there was no more object logging in these cases. Are you sure you didn't miss it?

**Comment by westwoodpr** [comment]
I tried clicking the magnifying glass again and found an "object" in the console "logs" tab:

{
  "renderAtt": [
    {
      "formattedSize": "133 KB",
      "thumb": "chrome://conversations/skin/icons/application-pdf.svg",
      "imgClass": "mime-icon",
      "name": "Q  139558.pdf",
      "url": "imap://.................redacted...................................:993/fetch%3EUID%3E/INBOX%3E118580?part=1.2&filename=Q%20%20139558.pdf",
      "anchor": "msg0att0",
      "isPdf": true,
      "maybeViewable": false
    }
  ]
}

**Comment by snowbound** [comment]
Spent an hour after upgrading to 68.x from 60.x of Thunderbird only to discover that any attachments sent with email to people are only visible via the Classic Reader option. Incoming mail with attachments has no such issue. I still see the Attachment Panel at the bottom of the message. Using 2.15.9 of Thunderbird Conversations.

**Comment by Standard8** [comment]
I think I've now found a solution. It appears there is a bug in Thunderbird that we're hitting possibly, with small attachments. I'm not 100% sure that is the exact case. The good news is I've found a way to work around it which I think should work - it does for all the cases I've tried.

Can someone who's been having this issue try the [new version available here](https://www.thebanners.uk/conversations-2.15.11.zip)?

If that works, then I'll publish it, and we'll see how it goes.

**Comment by snowbound** [comment]
I installed it but in order to work around the issue of not seeing attachments in sent email, I enabled the viewing of attachments inline. After adding the test build I can not seem to be able to find the wizard to disable the inline display of attachments.

**Comment by Standard8** [comment]
I went ahead and pushed the new version to the add-ons server for review. Seeing as it fixes at least something for me, it seemed best to get it out. Hopefully it'll be reviewed in a day or so.

If there's still issues with attachments after this, please file a new issue and try and include information about the attachment type and any log messages.
