### ISSUE TITLE
'From' account confusion

### ISSUE THREAD

**Issue by klapanciusz** [protz/thunderbird-conversations#1730]
Conversations confuses my accounts, but not always. Of course, it is possible that the issue is not actually in Conversation but in Thunderbird, only gets exposed when having Conversations installed. I get an email to my work email and when replying, it sometimes leaves from my personal email, and vice versa. Not always, I could not establish the pattern yet. Unfortunately, this was causing many problems. When I disabled Conversations, the problem was gone. I turned it on, the problem is back. Tried it with a disabled quick reply too, as it started in 4.0.0, when the quick reply was re-introduced. But I still don't have a clear pattern...

* **Thunderbird version:**: 91.2.1 EN-GB 64-bit
* **Thunderbird Conversation version:**: 4.0.1
* **Operating System:**: Win 10 64-bit

**What did you do?**: Replied to a message sent to me (or to a message I sent to someone else).

**What did you expect to happen?**: That the reply goes from the account to which I have received the message (which was used in the thread) or from which I was replying in the previous message.

**What actually happened?**: The response went from my other account (personal substituted with work email and vice versa). Not always, perhaps a fraction of cases around 10%. Have not observed a pattern yet when, and could not reliably replicate the problem.

**Comment by x-ji** [comment]
I would also like to report this issue. AFAIK it wasn't the case when I first started using the extension, but it broke a while ago. I had a couple of emails sent out from my Gmail (used only for newsletters and subscriptions) while they should have been sent from the personal inbox linked to my website.

If I right click the message and choose the usual "reply to the sender only" or "reply to all" from the TB context menu, it chooses the right sender address by default. However, the wrong sender address is chosen if I click on the Reply icon in the conversation view.

**Comment by Standard8** [comment]
@x-ji Please can you file a new issue as this one is closed. In particular, please can you provide more specific detail, I will not be able to do anything without specifics, e.g.

* The way the email was addressed (which emails in to/cc/bcc)
* The emails associated to your account/identities which were referenced (or not) in the email.
* If the email is in a folder in the account you received it from
* The email/identity that Thunderbird picks vs the one that Conversation picks.

I do not need to know the real email addresses - just an indication along the lines of, "I have an account with default email 'a' and additional identity 'b'" etc.

**Comment by x-ji** [comment]
Sure. I thought the original reporter also mentioned that the issue wasn't resolved for him either. I'll open a new issue and also cc him.

**Comment by x-ji** [comment]
Opened #1749
